
development: &dev
  github:
    key: 592cd23d78131215954c
    secret: 951c3b87f8798128f4fac6b9553ea92269edc515
  twitter:
    key: vq2lHLDRvLiPbzZ3nK1w9w
    secret: UwBNthASXPtaXSPR7tGfzYHqX2F4eFjvbXtepQ1YMKA

test:
  <<: *dev
